spring.application.name=gestione-pagamenti-restclient
server.port=${SERVER_PORT:8080}
server.servlet.context-path=/api

# Datasource (DB)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update

# RabbitMQ
spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.max-attempts=${RABBITMQ_RETRY_MAX_ATTEMPTS:10}
spring.rabbitmq.listener.simple.retry.initial-interval=${RABBITMQ_RETRY_INITIAL_INTERVAL:2000}s
spring.rabbitmq.listener.simple.retry.multiplier=${RABBITMQ_RETRY_MULTIPLIER:1.1}